name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          # Defaults to the user or organization that owns the workflow file
          scope: '@autoshark-finance'

      - name: Install dependencies
        run: yarn install

      - name: Run Build
        run: yarn build

      - name: Run Release
        run: git stash && git config --global user.email "you@example.com" && git config --global user.name "Your Name" && npm login --registry=https://npm.pkg.github.com --scope=@autoshark-finance && yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
